# This workflow is for a one-time, manual build of the ONNX model.
# It builds the model and commits the files back to the repository.
name: Build and Commit ONNX Model

on:
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # R31: FIX - Corrected the action name from 'setup-build-action' to 'setup-buildx-action'.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the builder image
        run: docker build -f Dockerfile.builder -t onnx-builder .

      - name: Create a temporary container from the builder
        run: docker create --name temp_builder onnx-builder

      - name: Copy the /onnx_model artifact from the container
        run: docker cp temp_builder:/onnx_model ./onnx_model

      - name: Verify that files were copied
        run: |
          echo "Listing contents of ./onnx_model:"
          ls -lR ./onnx_model

      - name: Configure Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add files to commit
        run: git add onnx_model

      - name: Commit and push the ONNX model files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add pre-built ONNX model files"
