# This workflow builds the ONNX model and uploads it as a release asset.
# This is a one-time, manual process.
name: Build and Release ONNX Model

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      # This permission is required to create a release.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the builder image
        run: docker build -f Dockerfile.builder -t onnx-builder .

      - name: Create a temporary container from the builder
        run: docker create --name temp_builder onnx-builder

      - name: Copy the /onnx_model artifact from the container
        run: docker cp temp_builder:/onnx_model ./onnx_model

      - name: Create a tarball of the model files
        # This creates a clean, simple archive.
        run: tar -czvf onnx_model.tar.gz onnx_model

      - name: Create GitHub Release and Upload Asset
        # This action creates a new release and attaches our tarball to it.
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          name: ONNX Model ${{ github.event.inputs.release_version }}
          body: "Pre-built and quantized ONNX model files for the application."
          files: onnx_model.tar.gz
