# This workflow is a one-time, manual process to build the ONNX model
# and commit the files to the repository using Git LFS.
# It is 100% self-contained and requires no local setup.
name: Build and Commit ONNX Model with LFS

on:
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the builder image
        run: docker build -f Dockerfile.builder -t onnx-builder .

      - name: Create a temporary container from the builder
        run: docker create --name temp_builder onnx-builder

      - name: Copy the /onnx_model artifact from the container
        run: docker cp temp_builder:/onnx_model ./onnx_model

      - name: Verify that files were copied
        run: ls -lR ./onnx_model

      # --- NEW SELF-CONTAINED GIT LFS SETUP ---

      - name: Set up Git LFS
        # This step installs Git LFS on the runner.
        run: git lfs install

      - name: Configure Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create .gitattributes file and track large files
        # This is the step that you would have done locally. We now do it in the workflow.
        # It tells Git which files to handle with LFS.
        run: |
          git lfs track "onnx_model/*.onnx"
          git lfs track "onnx_model/*.safetensors"
          # Ensure the .gitattributes file itself is added to the commit
          git add .gitattributes

      - name: Add model files to commit
        # Now we add the model directory. Git will see the tracking rules
        # from .gitattributes and handle the large files correctly.
        run: git add onnx_model

      - name: Commit and push the ONNX model files
        # This action will now commit both the .gitattributes file and the LFS pointer files,
        # while the large files are uploaded to LFS storage in the background.
        uses: stef
