# This workflow is for a one-time, manual build of the ONNX model.
# It builds the model and commits the files back to the repository.
name: Build and Commit ONNX Model

# This makes the workflow manually triggerable from the GitHub Actions UI.
on:
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    
    # Grant permissions to write back to the repository.
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the builder image
        # We build the builder Dockerfile which creates the /onnx_model directory.
        run: docker build -f Dockerfile.builder -t onnx-builder .

      - name: Create a temporary container from the builder
        # We create a container so we can copy the files out of it.
        run: docker create --name temp_builder onnx-builder

      - name: Copy the /onnx_model artifact from the container
        # We extract the finished product to a local directory.
        # We name the directory 'onnx_model' to be clear.
        run: docker cp temp_builder:/onnx_model ./onnx_model

      - name: Commit and push the ONNX model files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add pre-built ONNX model files"
          # The directory to add to the commit.
          file_pattern: onnx_model/*
          # The branch to push to.
          branch: main
