# R28 (NEW): Reverting to a single build-and-push step and disabling provenance
# to ensure a clean and fast push of ONLY the final, thin image layers.
name: Build and Publish Docker Image to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # R28: FIX - Use a single, unified step to build and push.
      # This is the most reliable method.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Push directly to the registry.
          push: true
          # Define the tags for the image.
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          # Still use the GHA cache for build performance.
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # This is the key: Disable provenance to prevent linking build cache metadata
          # to the final image manifest. This ensures a clean push.
          provenance: false
