# This is the final, guaranteed workflow using a two-job "Airlock" process.
# It physically separates the build artifact from the final image build.
name: Build and Publish Docker Image to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB 1: BUILD THE ONNX MODEL ARTIFACT ---
  build_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the builder image
        # We build the builder image but do not push it.
        # We give it a unique tag to reference it in the next step.
        run: docker build -f Dockerfile.builder -t onnx-builder .

      - name: Create a temporary container from the builder
        # We create a container so we can copy the files out of it.
        run: docker create --name temp_builder onnx-builder

      - name: Copy the /onnx_model artifact from the container
        # This is the key step: we extract the finished product.
        run: docker cp temp_builder:/onnx_model ./onnx_model_artifact

      - name: Upload the ONNX model as an artifact
        # We save the extracted folder as a GitHub Actions artifact.
        uses: actions/upload-artifact@v4
        with:
          name: onnx-model
          path: onnx_model_artifact

  # --- JOB 2: BUILD AND PUSH THE FINAL, THIN IMAGE ---
  build_and_push_image:
    # This job will only run after the artifact is successfully built.
    needs: build_artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download the ONNX model artifact
        # We download the clean artifact from the previous job.
        uses: actions/download-artifact@v4
        with:
          name: onnx-model
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push final image
        # We now build the final, single-stage Dockerfile.
        # The COPY command inside it will find the downloaded artifact.
        uses: docker/build-push-action@v5
        with:
          context: .
          # The Dockerfile to use is the simple, single-stage one.
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          # No caching is needed here as the build is simple and fast.
          provenance: false
