# This is the main, automated workflow. It downloads the model from a GitHub Release.
name: Build and Publish Application Docker Image

on:
#  push:
#    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download the ONNX model from the latest release
        # This action finds the latest release and downloads our specific asset.
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          repo: ${{ github.repository }}
          version: "latest" # Always get the latest release
          file: "onnx_model.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract the model tarball
        run: tar -xzvf onnx_model.tar.gz

      - name: Verify downloaded artifact
        run: ls -lR onnx_model

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push final image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          provenance: false
