# R29: This workflow is simplified to its core function: build from scratch and push.
# ALL CACHING MECHANISMS HAVE BEEN REMOVED as per user instruction.
name: Build and Publish Docker Image to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This is the simplest possible build and push step.
      # It will be slower on each run, but it will be clean and predictable.
      - name: Build and push Docker image (no cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          # R29: All cache-from and cache-to lines have been removed.
          # We also disable provenance to ensure the cleanest possible manifest.
          provenance: false
